
version: 2

models:
  - name: dim_customer
    config:
      contract:
        enforced: true
    description: "the customer dimension table"
    columns:
      - name: customer_id
        description: "unique identifier for each customer"
        data_type: int8
        data_tests:
          - unique
          - not_null

      - name: customer_name
        description: "Customer's full legal name."
        data_type: string
        data_tests:
          - unique
          - not_null

      - name: email
        description: "Customer email address."
        data_type: varchar
        data_tests:
          - not_null
          - unique
          - regex_match:
              arguments:
                column_name: email
                pattern: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"


      - name: phone_number
        description: "Customer phone number in flexible formats, including extensions."
        data_type: varchar

      - name: created_at
        description: "Timestamp when the customer record was created."
        data_type: timestamp
        constraints:
          - type: not_null
        data_tests:
          - not_null

      - name: modified_at
        description: "Timestamp when the customer record was last updated in the source system."
        data_type: timestamp
        data_tests:
          - not_null


  - name: dim_product
    description: "product dimension table"
    columns:
      - name: product_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: fct_orders
    description: "Order-level information including order dates and status"
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_id
      - name: order_status
        data_tests:
          - not_null
          - accepted_order_types

  - name: fct_events
    description: "Fact table of user events"
    columns:
      - name: event_type
        data_tests:
          - not_null
          - accepted_event_types

  - name: int_session
    description: "{{ doc('int_session') }}"

    columns:
      - name: session_break
        description: >
          Flag indicating whether the event starts a new session.
          A value of 1 means the inactivity gap from the previous event
          for the same customer exceeds 30 minutes; otherwise 0.

      - name: session_id
        description: >
          Sequential session identifier scoped to each customer.
          Generated by cumulatively summing session breaks in chronological order.

  - name: int_last_session_per_customer
    description: "{{ doc('int_last_session_per_customer') }}"

    columns:
      - name: last_session_id
        description: >
          Identifier of the most recent session for the customer, derived as the maximum session ID.

  - name: int_session_bounds
    description: "{{ doc('int_session_bounds') }}"

  - name: int_check_order
    description: "{{ doc('int_check_order') }}"
    columns:
      - name: order_id
        description: Identifier of the order placed within the last session.

  - name: int_cart_value
    description: "{{ doc('int_cart_value') }}"




