version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: customer
        identifier: stg_customer
        description: "Customer information including email, phone numbers and IDs"

      - name: orders
        identifier: stg_orders
        description: "Order-level information including order dates and status"
        config:
          loaded_at_field: modified_at
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}

      - name: order_item
        identifier: stg_orderitem
        description: "Line items in orders including product, quantity, and price"


      - name: event
        identifier: stg_event
        description: "User events for session tracking"
        config:
          loaded_at_field: modified_at
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}

      - name: product
        identifier: stg_product
        description: "product description showing brand and available discounts"